version: '2'
services:
  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MEMORY_LIMIT=128
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
#
#  tarantool:
#    image: 'tarantool/tarantool:1.7'
#    ports:
#      - "3302:3301"


